#PANDAS

In [1]:
!pip install pandas    #python install package

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
#creating a dataframe

In [4]:
data = {'Name': ['Arya', 'Govardhan', 'Tushar'],
        'Age':[24,28,33],
        'City': ['wardha', 'washim', 'nagpur']}

In [5]:
data

{'Name': ['Arya', 'Govardhan', 'Tushar'],
 'Age': [24, 28, 33],
 'City': ['wardha', 'washim', 'nagpur']}

In [6]:
type(data)

dict

In [7]:
df = pd.DataFrame(data)

In [8]:
df

        Name  Age    City
0       Arya   24  wardha
1  Govardhan   28  washim
2     Tushar   33  nagpur

In [9]:
#list to df

In [11]:
list1 = [['arya', 23, 'wardha'], ['govardhan', 28, 'washim'], ['tushar', 33, 'nagpur']]

In [12]:
df1 = pd.DataFrame(list1, columns = ['Name', 'Age', 'City'])

In [13]:
df1

        Name  Age    City
0       arya   23  wardha
1  govardhan   28  washim
2     tushar   33  nagpur

In [15]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [16]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [17]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [18]:
df.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0

In [19]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [21]:
df.info()      #dataframe structure info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [22]:
df.describe()      #to check mean, mode, max , all statastic values

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [23]:
df['longitude']

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64

In [26]:
df[['longitude', 'latitude']]    #each column

       longitude  latitude
0        -114.31     34.19
1        -114.47     34.40
2        -114.56     33.69
3        -114.57     33.64
4        -114.57     33.57
...          ...       ...
16995    -124.26     40.58
16996    -124.27     40.69
16997    -124.30     41.84
16998    -124.30     41.80
16999    -124.35     40.54

[17000 rows x 2 columns]

In [27]:
df.iloc[16992]             #by index location/ index number

longitude              -124.2300
latitude                 40.8100
housing_median_age       52.0000
total_rooms            1112.0000
total_bedrooms          209.0000
population              544.0000
households              172.0000
median_income             3.3462
median_house_value    50800.0000
Name: 16992, dtype: float64

In [29]:
df.loc[16992]      #by label index name location

longitude              -124.2300
latitude                 40.8100
housing_median_age       52.0000
total_rooms            1112.0000
total_bedrooms          209.0000
population              544.0000
households              172.0000
median_income             3.3462
median_house_value    50800.0000
Name: 16992, dtype: float64

In [30]:
# filter data by condition - latitude > 40

In [32]:
filtered_df = df[df['latitude']> 40]

In [33]:
filtered_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10315,-120.08,41.79,34.0,1355.0,262.0,434.0,178.0,2.0903,56100.0
10348,-120.12,41.40,33.0,2820.0,515.0,976.0,403.0,2.6062,52600.0
10388,-120.20,40.26,26.0,2399.0,518.0,1037.0,443.0,2.6765,47600.0
10450,-120.35,40.63,33.0,240.0,49.0,63.0,22.0,3.6250,200000.0
10461,-120.37,40.17,21.0,789.0,141.0,406.0,146.0,2.1198,73500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [35]:
filtered_df = df[(df['latitude']> 40) & (df['latitude'] < 41)]

In [36]:
filtered_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10388,-120.20,40.26,26.0,2399.0,518.0,1037.0,443.0,2.6765,47600.0
10450,-120.35,40.63,33.0,240.0,49.0,63.0,22.0,3.6250,200000.0
10461,-120.37,40.17,21.0,789.0,141.0,406.0,146.0,2.1198,73500.0
10470,-120.38,40.98,27.0,777.0,185.0,318.0,115.0,1.6833,40000.0
10504,-120.42,40.38,26.0,1652.0,313.0,762.0,280.0,2.4757,85600.0
...,...,...,...,...,...,...,...,...,...
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [37]:
df['New_House_Age'] = df['housing_median_age'] + 5    #create a new column in given system

In [38]:
df.head(1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_House_Age
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,20.0

In [39]:
df.isnull()    #missing value are have or not

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_House_Age
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
16995,False,False,False,False,False,False,False,False,False,False
16996,False,False,False,False,False,False,False,False,False,False
16997,False,False,False,False,False,False,False,False,False,False
16998,False,False,False,False,False,False,False,False,False,False
16999,False,False,False,False,False,False,False,False,False,False

In [41]:
df.isnull().sum()       #count missing value

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
New_House_Age         0
dtype: int64

In [42]:
df.dropna(inplace= True)     # drop rows with missing value & na means null value

In [44]:
df.fillna(value= 13, inplace = True)    #fill the missing values with specific 13